#!/usr/bin/env bash

# This file is part of the 19blog project.
# 19blog is a simple blog site system.
# Copyright (C) 2020  The 19blog Authors.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# The user register page.

# --includes
. "$(dirname "${BASH_SOURCE[0]}")/../util/home"

# --do not open user registration
if [ -z "$user" ]; then
    # show close button when error
    ERRCLOSE=true
    resErr "User registration is not yet open. Please contact administrator."
fi

# tag for refresh home page or not
refreshHome=false

# --save data from post
if [ "$REQUEST_METHOD" = 'POST' ]; then
    # save user
    if ! saveUser "${uparam["name"]}" "${uparam["password"]}" "${uparam["memo"]}"; then
        resErr "Save user failed"
    fi

    # continue to edit and refresh home page
    refreshHome=true
fi

# output template regist.html
resFile "$(dirname "${BASH_SOURCE[0]}")/regist.html"
