#!/usr/bin/env bash

# This file is part of the flblog project.
# flblog is a simple blog site system.
# Copyright (C) 2020  The flblog Authors.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# The home page for administrator

# --includes
. "$(dirname "${BASH_SOURCE[0]}")/../util/home"

# tag for refresh home page or not
refreshHome=false

# --save data from post
if [ "$REQUEST_METHOD" = 'POST' ]; then
    # save config
    if ! saveConfig "${uparam["title"]}" "${uparam["memo"]}"; then
        resErr "Save config failed"
    fi
    # save or remove ads left
    if ! saveAD "l" "${uparam["adsl_url"]}" "${uparam["adsl_html"]}"; then
        resErr "Save or remove ads left failed"
    fi
    # save or remove ads right
    if ! saveAD "r" "${uparam["adsr_url"]}" "${uparam["adsr_html"]}"; then
        resErr "Save or remove ads right failed"
    fi

    # continue to edit and refresh home page
    refreshHome=true

    res303
fi

# get config info
getConfig
# get ads left
getAD "l"
# get ads right
getAD "r"

# the tile and memo will expand in index.html
resFile './index.html'
