#!/usr/bin/env bash

# --Output standard file header
echo "Content-Type: text/html; charset=UTF-8"
echo

# --fastcgi params list
#
# fastcgi_param  SCRIPT_FILENAME    $document_root$fastcgi_script_name;
# fastcgi_param  QUERY_STRING       $query_string;
# fastcgi_param  REQUEST_METHOD     $request_method;
# fastcgi_param  CONTENT_TYPE       $content_type;
# fastcgi_param  CONTENT_LENGTH     $content_length;
#
# fastcgi_param  SCRIPT_NAME        $fastcgi_script_name;
# fastcgi_param  REQUEST_URI        $request_uri;
# fastcgi_param  DOCUMENT_URI       $document_uri;
# fastcgi_param  DOCUMENT_ROOT      $document_root;
# fastcgi_param  SERVER_PROTOCOL    $server_protocol;
# fastcgi_param  REQUEST_SCHEME     $scheme;
# fastcgi_param  HTTPS              $https if_not_empty;
#
# fastcgi_param  GATEWAY_INTERFACE  CGI/1.1;
# fastcgi_param  SERVER_SOFTWARE    nginx/$nginx_version;
#
# fastcgi_param  REMOTE_ADDR        $remote_addr;
# fastcgi_param  REMOTE_PORT        $remote_port;
# fastcgi_param  SERVER_ADDR        $server_addr;
# fastcgi_param  SERVER_PORT        $server_port;
# fastcgi_param  SERVER_NAME        $server_name;
#
# fastcgi_param REMOTE_USER         $remote_user;
# fastcgi_param PATH_INFO           $1;

# --decode query param value
function urldecode() {
  : "${*//+/ }"
  echo -e "${_//%/\\x}"
}

# --pasrse qurey params
# need bash v4.0+
declare -A uparam
function parseQuery() {
  while IFS='=' read -r -d '&' key value && [[ -n "$key" ]]; do
    uparam["$key"]=$(urldecode "$value")
  done <<<"${*}&"
}
parseQuery "$QUERY_STRING"


# --test
#parseQuery "client=firefox-b-d&ei=sT7fX5CPAYfahwPWsJko&q=bash+%E5%B0%86%E5%8F%98%E9%87%8F%E5%86%99%E5%85%A5%E6%96%87%E4%BB%B6&oq=bash+%E5%B0%86%E5%8F%98%E9%87%8F%E5%86%99%E5%85%A5%E6%96%87%E4%BB%B6&gs_lcp=CgZwc3ktYWIQA1D152pYrLhrYPa5a2gAcAB4AIABtjyIAd9ekgENMy0xLjEuMC4xLjktMpgBAKABAaoBB2d3cy13aXrAAQE&sclient=psy-ab&ved=0ahUKEwjQq-KSw9ztAhUH7WEKHVZYBgUQ4dUDCAw&uact=5"
cat <<EOF
<div style='background-color: #71f5f5; border: #999 solid 1px; padding: 5px;'>
<p>uparam names: ${!uparam[*]}</p>
<p>query_string: $QUERY_STRING</p>
<p>content_type: $CONTENT_TYPE</p>
<p>post body: <br/>
<pre>$(cat)</pre>
</p>
</div>
EOF
