#!/usr/bin/env bash

# The main page for user admin.
# Provide the following operations:
#   1. Add blog;

. ./util/http
. ./util/fcgi
. ./util/common

res200

# show close button when error
ERRCLOSE=true

# remove blog
rmBlog "${uparam["id"]}"

# output template remove.html
resFile './remove.html'
