#!/usr/bin/env bash

# This file is part of the 19blog project.
# 19blog is a simple blog site system.
# Copyright (C) 2020  The 19blog Authors.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# common functions
# Dependent files:
#       ./http
# NOTE: should be sourced once at any cgi interface
# NOTE: all of functions must called in main shell,
#       and the result is $RET.
#       because error check in function,
#       and terminate response directly when error ocurse.

# --directories
rundir=$(dirname "$0")
cgidir=$(dirname "$rundir")
rootdir=$(dirname "$cgidir")
templdir="$cgidir/templ"
homedir="$rootdir/home"
blogsdir="$rootdir/blogs"
configdir="$blogsdir/config"
totalfile="$configdir/total"
mkdir -p "$configdir"
if [ ! -e "$totalfile" ]; then
    echo "all 0" >"$totalfile"
fi

# --check current user
function curUser() {
    if [ -z "$REMOTE_USER" ]; then
        resErr 'Current user is empty.'
    fi
    RET=$REMOTE_USER
}

# --get current user's file
#   if file does not exsit, copy templ file to it
#   if file cannot be write, print error msg and terminate
#   $1  file path
#   $2  templ path
#   result is $1
function curFile() {
    curUser && user=$RET
    if [ ! -e "$1" ]; then
        if ! cp "$2" "$1"; then
            resErr "Can not copy template file[$2] to $user's file[$1]."
        fi
        # write user name to blog file
        sed -i "s/<!--user-->/$user/g" "$1"
    fi
    if [ ! -w "$1" ]; then
        resErr "Can not write to $user's file[$1]."
    fi
    RET=$1
}