#!/usr/bin/env bash

# This file is part of the flblog project.
# flblog is a simple blog site system.
# Copyright (C) 2020  The flblog Authors.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# blog edit
# GET:
#   id == NULL -> add
#   id != NULL -> edit
# POST:
#   id == NULL -> save new
#   id != NULL -> save edit

# --includes
. "$(dirname "${BASH_SOURCE[0]}")/../util/blog"

# tag for refresh blog list or not
refreshList=false

# var for html
date="$(date "+%H:%M %m/%d/%Y")"

id=${uparam["id"]}

# --save blog from post
if [ "$REQUEST_METHOD" = 'POST' ]; then
    if [ "${uparam["publish"]}" = '1' ]; then # publish blog
        if draftPublish "$id" "${uparam["title"]}" "${uparam["content"]}"; then
            # output template succ.html to refresh list and close page
            refreshList=true
            resFile './succ.html'
            exit 0
        else
            resErr "Publish failed"
        fi
    else # save blog
        if draftSave "$id" "${uparam["title"]}" "${uparam["content"]}"; then
            # continue to edit and refresh list
            refreshList=true
        else
            resErr "Save failed"
        fi
    fi
fi

if [ -n "$id" ]; then
    # show close button when error
    ERRCLOSE=true

    # get blog content
    draftContent "$id"

    # make remove button
    rmbtn="<input class='button remove' type='button' value='Remove' onclick='onRemove()'>"
    # make publish button
    plbtn="<input class='button publish' type='button' value='Publish' onclick='onPublish()'>"
fi

# the id tile and content will expand in edit.html
resFile './edit.html'
