#!/usr/bin/env bash

# This file is part of the 19blog project.
# 19blog is a simple blog site system.
# Copyright (C) 2020  The 19blog Authors.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# blog edit
# GET:
#   id == NULL -> add
#   id != NULL -> edit
# POST:
#   id == NULL -> save new
#   id != NULL -> save edit

. ../util/http
. ../util/fcgi
. ../util/common
. ../util/blog

res200

# tag for refresh blog list or not
refreshList=false

# var for html
date=$(date "+%H:%M %m/%d/%Y")

id=${uparam["id"]}

# --save blog from post
if [ "$REQUEST_METHOD" = 'POST' ]; then
    if draftSave "$id" "${uparam["title"]}" "${uparam["content"]}"; then
        # continue to edit and refresh list
        refreshList=true
    else
        resErr "Save failed"
    fi
fi

if [ -n "$id" ]; then
    # show close button when error
    ERRCLOSE=true

    # get blog info
    draftBlog "$id"

    # make remove button
    rmbtn="<input class='button remove' type='button' value='Remove' onclick='onRemove()'>"
fi

# the id tile and content will expand in edit.html
resFile './edit.html'
